Models/Case.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Caseowary.Models
{
    public enum CaseStatusCode
    {
        ProblemSolved = 5,
        InformationProvided = 1000,
        Canceled = 6,
        InProgress = 1,
        OnHold = 2,
        WaitingforDetails = 3,
        Researching = 4
    }

    public class CaseModel
    {
        public Guid PrimaryKey { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
        public CaseStatusCode Status { get; set; }

        public string StatusName
        {
            get
            {
                return Status.ToString();
            }
        }
    }

    public class CaseViewModel
    {
        public IEnumerable<CaseModel> Cases;
        public string Username;
        public Guid UserId;
    }
}

Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Services;
using System.IdentityModel.Services.Configuration;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Caseowary.Controllers
{
    public class AccountController : Controller
    {
        public ActionResult SignOut()
        {
            WsFederationConfiguration config = FederatedAuthentication.FederationConfiguration.WsFederationConfiguration;

            // Redirect to SignOutCallback after signing out.
            string callbackUrl = Url.Action("SignOutCallback", "Account", routeValues: null, protocol: Request.Url.Scheme);
            SignOutRequestMessage signoutMessage = new SignOutRequestMessage(new Uri(config.Issuer), callbackUrl);
            signoutMessage.SetParameter("wtrealm", IdentityConfig.Realm ?? config.Realm);
            FederatedAuthentication.SessionAuthenticationModule.SignOut();
            
            IdentityConfig.Current.ResetTokens();
            return new RedirectResult(signoutMessage.WriteQueryString());
        }

        public ActionResult SignOutCallback()
        {
            if (Request.IsAuthenticated)
            {
                // Redirect to home page if the user is authenticated.
                return RedirectToAction("Index", "Home");
            }
            
            IdentityConfig.Current.ResetTokens();

            return View();
        }
    }
}

Controllers/CaseController.cs
using Caseowary.Models;
using Caseowary.Utils;
using Caseowary.Xrm;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace Caseowary.Controllers
{
    public class CaseController : Controller
    {
        // GET: /Case/
        public ActionResult Index()
        {
            IdentityConfig ic = IdentityConfig.Current;
            if (ic.IsAuthenticated)
            {
                Guid userId = Helper.GetUserId(ic.TokenResult.AccessToken);
                ViewBag.Username = Helper.GetUserName(ic.TokenResult.AccessToken, userId);

                var service = Helper.GetODataService(ic.TokenResult.AccessToken);
                var cases = service.IncidentSet
                    .Where( c => c.OwnerId.Id == userId)
                    .Select(c => 
                        new CaseModel() 
                        { 
                            PrimaryKey = c.IncidentId, 
                            Title = c.Title, 
                            Number = c.TicketNumber, 
                            Status = (CaseStatusCode)c.StatusCode.Value.GetValueOrDefault(1) 
                        })
                    .ToList();
                
                return View(cases);
            }
            else
            {
                Session["ReturnUrl"] = Request.Url.AbsoluteUri;
                return new RedirectResult(ic.GetAuthorizationUrl());
            }
        }

        // GET: /Case/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Case/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Case/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Case/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Case/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Case/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Case/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Caseowary.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Caseowary is confined to the jungle areas of North Queensland.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Where to find caseowaries.";

            return View();
        }
        public ActionResult SignIn()
        {
            // simply redirect to root (after the login). login will be forced by <authorization> element in web.config
            return new RedirectResult("/");
        }

    }
}

Controllers/ReplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Caseowary.Utils;
using System.Configuration;

namespace Caseowary.Controllers
{
    public class ReplyController : Controller
    {
        //
        // GET: /Reply/
        public ActionResult Index(string code)
        {
            IdentityConfig.Current.AcquireToken(code);
            var url = "/";
            if (Session["ReturnUrl"] != null)
            {
                url = (string)Session["ReturnUrl"];
                Session["ReturnUrl"] = null;
            }
            return new RedirectResult(url);
        }
	}
}

Views/Case/Index.cshtml
@model IEnumerable<Caseowary.Models.CaseModel>

@{
    ViewBag.Title = "Cases";
}
<h1>Cases owned by you, @ViewBag.Username</h1>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().StatusName)
        </th>
        <th></th>
    </tr>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}
    
</table>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Cassowaries have a reputation for being dangerous to people and domestic animals.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact us";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Caseowary</h1>
    <p class="lead">The caseowaries (IPA: /,keɪsɵwæri/) are ratites (flightless birds without a keel on their sternum bone) in the genus <em>Casuarius</em> native to the tropical forests of New Guinea, nearby islands, and northeastern Australia. </p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Description</h2>
        <p>
            The Northern and Dwarf Cassowaries are not well known. All cassowaries are usually shy birds of the deep forest, adept at disappearing long before a human knows they are there.
            </p>
        <p>There are three extant species recognized today. 
</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Distribution and habitat</h2>
        <p>The most common of these, the Southern caseowary, is the third tallest and second heaviest living bird, smaller only than the ostrich and emu.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Behaviour and ecology</h2>
        <p>Caseowaries feed mainly on fruit, although all species are truly omnivorous and will take a range of other plant food including shoots, and fungi in addition to invertebrates and small vertebrates. Caseowaries are very shy, but when provoked they are capable of inflicting injuries to dogs and people.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AAD Authentication Sample</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Caseowary", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Cases", "Index", "Case")</li>
                    <li><a href="@System.Configuration.ConfigurationManager.AppSettings["OrgUrl"]" target="_blank">CRM</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AAD Authentication Sample</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>